version: '3'

services:
  tests:
    container_name: lis-tests
    build: 
      context: .
      dockerfile: Dockerfile.tests
    environment:
      - API_URL=http://api:5000   
    entrypoint: dotnet test
    depends_on:
      - api
  api:
    container_name: lis-api
    build: .
    ports: 
      - 5000:5000
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    entrypoint: dotnet /app/Api.dll

